name: Pip.Services Entities microservice in Node.JS

on: 
  push:
    paths:
    - '**'
    - '!README.md'

jobs:
  Default:
    runs-on: ubuntu-18.04
    env:
        GIT_PRIVATE_KEY: ${{ secrets.GIT_PRIVATE_KEY }}
        
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
    - uses: actions/checkout@main

  
    ############# Prepare #############

    - name: Install prereq and save build number
      id: build_info
      uses: pip-devops/actions/node/prepare@v1


    # ############# Build and test #############

    - name: Build the component
      uses: pip-devops/actions/node/build@v1

    - name: Test the component
      uses: pip-devops/actions/node/test@v1

    ############# Clear #############

    - name: Clean up
      uses: pip-devops/actions/node/clear@v1
